ALL_NODE_COMBINATIONS: false
BOND_TOL: 12.0
CHARGES: true
COMBINATORIAL_EDGE_ASSIGNMENT: true
CONNECTION_SITE_BOND_LENGTH: 1.54
EXPANSIVE_BOND_SEARCH: true
FIX_UC: !!python/tuple [0, 0, 0, 0, 0, 0]
MERGE_CATENATED_NETS: true
NODE_TO_NODE: true
ONE_ATOM_NODE_CN: !!python/tuple
- true
- {C: 4, N: 3, Zn: 4}
ORIENTATION_DEPENDENT_NODES: false
OUTPUT_SCALING_DATA: true
PLACE_EDGES_BETWEEN_CONNECTION_POINTS: true
PRE_SCALE: 1.0
PRINT: false
RECORD_CALLBACK: false
RUN_PARALLEL: false
SCALING_CONVERGENCE_TOLERANCE: 1e-06
SCALING_ITERATIONS: 1
SCALING_STEP_SIZE: 1e-08
SINGLE_ATOM_NODE: true
SINGLE_METAL_MOFS_ONLY: false
SYMMETRY_TOL: {2: 0.1, 3: 0.3, 4: 1.0, 5: 0.5, 6: 0.5, 7: 0.5, 8: 0.5, 9: 0.5, 10: 0.5,
    12: 0.5, 24: 1.0}
TRACE_BOND_MAKING: false
USER_SPECIFIED_NODE_ASSIGNMENT: false
WRITE_CHECK_FILES: false
WRITE_CIF: true
SHIFT: true
MIN_DISTANCE: 0.5
MAX_NATOM: 600
